

class Solution {

    public int orangesRotting(int[][] grid) {

            int rows = grid.length;
                    int cols = grid[0].length;

                            Queue<int[]> queue = new ArrayDeque<>();

                                    int fresh = 0;

                                            // 1. Find all initially rotten oranges
                                                    //    and count fresh oranges
                                                            for (int r = 0; r < rows; r++) {
                                                                        for (int c = 0; c < cols; c++) {

                                                                                        if (grid[r][c] == 2) {
                                                                                                            queue.add(new int[]{r, c});
                                                                                                                            }

                                                                                                                                            if (grid[r][c] == 1) {
                                                                                                                                                                fresh++;
                                                                                                                                                                                }
                                                                                                                                                                                            }
                                                                                                                                                                                                    }

                                                                                                                                                                                                            int minutes = 0;

                                                                                                                                                                                                                    // Four possible directions:
                                                                                                                                                                                                                            // up, down, left, right
                                                                                                                                                                                                                                    int[][] directions = {
                                                                                                                                                                                                                                                {-1, 0},
                                                                                                                                                                                                                                                            {1, 0},
                                                                                                                                                                                                                                                                        {0, -1},
                                                                                                                                                                                                                                                                                    {0, 1}
                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                    // 2. BFS
                                                                                                                                                                                                                                                                                                            while (!queue.isEmpty() && fresh > 0) {

                                                                                                                                                                                                                                                                                                                        int size = queue.size();

                                                                                                                                                                                                                                                                                                                                    // Process all oranges that are rotten
                                                                                                                                                                                                                                                                                                                                                // at the beginning of this minute
                                                                                                                                                                                                                                                                                                                                                            for (int i = 0; i < size; i++) {

                                                                                                                                                                                                                                                                                                                                                                            int[] current = queue.poll();

                                                                                                                                                                                                                                                                                                                                                                                            int r = current[0];
                                                                                                                                                                                                                                                                                                                                                                                                            int c = current[1];

                                                                                                                                                                                                                                                                                                                                                                                                                            // Check all 4 neighbors
                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int[] direction : directions) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                int nr = r + direction[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int nc = c + direction[1];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Check if neighbor is inside grid
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (nr < 0 || nr >= rows ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    nc < 0 || nc >= cols) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // If fresh, make it rotten
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (grid[nr][nc] == 1) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                grid[nr][nc] = 2;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fresh--;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                queue.add(new int[]{nr, nc});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // One complete BFS level = one minute
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        minutes++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // If fresh oranges remain, impossible
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (fresh > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return minutes;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }